title: Filipe Crespo
description: > # this means to ignore newlines until "baseurl:"
  Sou Filipe Crespo, tenho 27 anos, nascido em Portugal e criado no Brasil.
  Já atuei em diversas áreas do mercado brasileiro de TI.
  Hoje sou desenvolvedor Php, Ruby e JavaScript, além disso me arrisco em projetos com Python, Node e VueJS.

permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://filipecrespodev.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Filipe Crespo # add your name
author-img: filipe-crespo-avatar.png # add your photo
about-author: Sou Filipe Crespo, tenho 27 anos, nascido em Portugal e criado no Brasil. Já atuei em diversas áreas do mercado brasileiro de TI. Hoje sou desenvolvedor Php, Ruby e JavaScript , além disso me arrisco em projetos com Python, Node e VueJS. # add description
social-twitter: filipecrespodev # add your Twitter handle
social-facebook: filipecrespodev # add your Facebook handle
social-github: filipecrespodev # add your Github handle
social-linkedin: filipescrespo # add your Linkedin handle
social-twitch: filipecrespodev # add your Twitch handle

# Tracker
analytics: UA-170278743-1 # Google Analytics

sass:
  sass_dir: _sass
  style: compressed

  # Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-coffeescript

paginate: 8
paginate_path: "/page/:num"

lang: pt-BR
languages: ["pt"]

exclude: ["vender"]
